repos:
# Can make do without this one tbh
- repo: https://github.com/asottile/pyupgrade
  rev: v3.10.1
  hooks:
    - id: pyupgrade
      args: [ --py39-plus]


- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.285
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix]

- repo: https://github.com/asottile/seed-isort-config
  rev: v2.2.0
  hooks:
    - id: seed-isort-config

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: [ -m, "3"] 


- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black

