name: Code Formatting

on:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install formatters
        run: |
          pip install ruff isort black

      - name: Auto-format with isort
        run: |
          isort .

      - name: Auto-format with Black
        run: |
          black .

      - name: Auto-fix with Ruff
        run: |
          ruff --fix --ignore E501 .

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          # Skip commit if no changes
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "Format code [skip ci]" && git push)