name: Code Formatting

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          token: ${{ secrets.ACTION_TOKEN }}

      - name: Install formatters
        run: |
          pip install ruff isort black

      - name: Auto-format with isort
        run: |
          isort .

      - name: Auto-format with Black
        run: |
          black .

      - name: Auto-fix with Ruff
        run: |
          ruff check . --fix --ignore E501

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          # Skip commit if no changes
          git diff --quiet && git diff --staged --quiet || \
            (git commit -m "refactor: format code [skip ci]" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
          
